function [fitresult, gof] = createFit(distance, avg)
%CREATEFIT(DISTANCE,AVG)
%  Create a fit.
%
%  Data for 'path loss' fit:
%      X Input : distance
%      Y Output: avg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Feb-2020 01:14:20


%% Fit: 'path loss'.
[xData, yData] = prepareCurveData( distance, avg );

% Set up fittype and options.
ft = fittype( '-10*n*log10(x/1)-50.5801', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.157613081677548;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'path loss' );
h = plot( fitresult, xData, yData );
legend( h, 'avg vs. distance', 'path loss', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'distance', 'Interpreter', 'none' );
ylabel( 'avg', 'Interpreter', 'none' );
grid on


