function [fitresult, gof] = createFit(distance, avg)
%CREATEFIT(DISTANCE,AVG)
%  Create a fit.
%
%  Data for 'pathloss' fit:
%      X Input : distance
%      Y Output: avg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Feb-2020 19:53:05


%% Fit: 'pathloss'.
[xData, yData] = prepareCurveData( distance, avg );

% Set up fittype and options.
ft = fittype( '-10 * n * log10(x) -54.2703', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.278498218867048;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'pathloss' );
h = plot( fitresult, xData, yData );
legend( h, 'avg vs. distance', 'pathloss', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'distance', 'Interpreter', 'none' );
ylabel( 'avg', 'Interpreter', 'none' );
grid on


